Switch to Docker actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,10 +20,10 @@ jobs:
     steps:
       -
         name: Checkout
-        uses: actions/checkout@v2.3.1
+        uses: actions/checkout@v2.3.2
       -
         name: Prepare
-        id: prepare
+        id: prep
         run: |
           echo ::set-output name=build_tag::test
           echo ::set-output name=container_name::ftpgrab
@@ -32,11 +32,11 @@ jobs:
       -
         name: Docker Build
         run: |
-          docker build --tag ${{ steps.prepare.outputs.build_tag }} --file Dockerfile .
+          docker build --tag ${{ steps.prep.outputs.build_tag }} --file Dockerfile .
       -
         name: Create network
         run: |
-          docker network create -d bridge ${{ steps.prepare.outputs.container_name }}
+          docker network create -d bridge ${{ steps.prep.outputs.container_name }}
       -
         name: Start Pure-FTPd container
         run: |
@@ -45,7 +45,7 @@ jobs:
           cat /tmp/pureftpd.passwd
 
           docker run -d --name pureftpd --hostname pureftpd \
-            --network ${{ steps.prepare.outputs.container_name }} \
+            --network ${{ steps.prep.outputs.container_name }} \
             -e "AUTH_METHOD=puredb" \
             -e "SECURE_MODE=false" \
             -v "${HOME}/warmup:/home/foo" \
@@ -58,33 +58,33 @@ jobs:
       -
         name: Start container
         run: |
-          docker run -d --name ${{ steps.prepare.outputs.container_name }} \
+          docker run -d --name ${{ steps.prep.outputs.container_name }} \
             --link pureftpd \
-            --network ${{ steps.prepare.outputs.container_name }} \
+            --network ${{ steps.prep.outputs.container_name }} \
             -e "SCHEDULE=*/30 * * * *" \
             -e "LOG_LEVEL=debug" \
             -e "LOG_NOCOLOR=true" \
             -v "$(pwd)/.res/ftpgrab.test.yml:/ftpgrab.yml:ro" \
-            ${{ steps.prepare.outputs.build_tag }}
+            ${{ steps.prep.outputs.build_tag }}
       -
         name: Test run
         run: |
-          TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
+          TIMEOUT=$((SECONDS + ${{ steps.prep.outputs.running_timeout }}))
           while read LOGLINE; do
             echo ${LOGLINE}
-            if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
+            if [[ ${LOGLINE} == *"${{ steps.prep.outputs.running_log_check }}"* ]]; then
               echo "🎉 Container up!"
               break
             fi
             if [[ $SECONDS -gt ${TIMEOUT} ]]; then
-              >&2 echo "❌ Failed to run ${{ steps.prepare.outputs.container_name }} container"
+              >&2 echo "❌ Failed to run ${{ steps.prep.outputs.container_name }} container"
               exit 1
             fi
-          done < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)
+          done < <(docker logs -f ${{ steps.prep.outputs.container_name }} 2>&1)
 
-          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prepare.outputs.container_name }})
+          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prep.outputs.container_name }})
           if [[ ${CONTAINER_STATUS} != "running" ]]; then
-            >&2 echo "❌ Container ${{ steps.prepare.outputs.container_name }} returned status '$CONTAINER_STATUS'"
+            >&2 echo "❌ Container ${{ steps.prep.outputs.container_name }} returned status '$CONTAINER_STATUS'"
             exit 1
           fi
       -
@@ -97,5 +97,5 @@ jobs:
         name: Container logs
         if: always()
         run: |
-          docker logs ${{ steps.prepare.outputs.container_name }}
-          docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+          docker logs ${{ steps.prep.outputs.container_name }}
+          docker rm -f ${{ steps.prep.outputs.container_name }} > /dev/null 2>&1 || true
